name: Simple Cache Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: prime-cache-bea82af
        id: cache-step
        uses: actions/cache@v4
        with:
          path: tmp-cache-folder
          key: cache-bea82af
          restore-keys: |
            cache-bea82af

      - name: Show cache result
        run: |
          if [ "${{ steps.cache-step.outputs.cache-hit }}" = "true" ]; then
            echo "Cache hit!"
          else
            echo "Cache miss!"
            mkdir -p tmp-cache-folder
            echo "Primed cache" > tmp-cache-folder/file.txt
          fi
